apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-log-deployment
spec:
  replicas: 3
#  strategy:
#    type: RollingUpdate
#    rollingUpdate:
#      MaxSurge: 25%
#      MaxUnavailable: 25%
  selector:
    matchLabels:
      app: log-app
  template:
    metadata:
      labels:
        app: log-app
    spec:
      containers:
      - name: log-app
        image: imlinux68/log_app:v1
